variables:
  JEKYLL_ENV: production
  WEBSITE_URL: https://www.4c-multiphysics.org
  PREVIEW_DIRECTORY: _preview

.build:
  image: ruby:3.3
  stage: build
  script:
    - bundle config set --local path 'vendor/bundle'
    - bundle install
    - "echo \"baseurl: $WEBSITE_ROOT_PATH\nurl: $WEBSITE_URL\" > config.yml"
    - bundle exec jekyll build -d website --config _config.yml,config.yml
    - cp .htaccess website/
  artifacts:
    paths:
      - website/
  tags:
    - docker

preview:
  extends: .build
  variables:
    WEBSITE_ROOT_PATH: /$PREVIEW_DIRECTORY/$CI_MERGE_REQUEST_IID
  rules:
    - if: $CI_MERGE_REQUEST_IID

production:
  extends: .build
  variables:
    WEBSITE_ROOT_PATH: ""
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish_preview:
  stage: deploy
  needs:
    - job: preview
      artifacts: true
  rules:
    - if: $CI_MERGE_REQUEST_IID
  script:
    - ssh di35non@webdev02-mwn.lrz.de mkdir -p /nfs/web_tum/www/n/di35non/webserver/htdocs/$PREVIEW_DIRECTORY/$CI_MERGE_REQUEST_IID
    # ensure password protection
    - rsync -rpt -e ssh $PREVIEW_DIRECTORY/ di35non@webdev02-mwn.lrz.de:/nfs/web_tum/www/n/di35non/webserver/htdocs/$PREVIEW_DIRECTORY
    - rsync -rpt -e ssh --delete website/ di35non@webdev02-mwn.lrz.de:/nfs/web_tum/www/n/di35non/webserver/htdocs/$PREVIEW_DIRECTORY/$CI_MERGE_REQUEST_IID


publish_production:
  stage: deploy
  needs:
  - job: production
    artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
  - rsync -rpt -e ssh --delete --exclude $PREVIEW_DIRECTORY website/ di35non@webdev02-mwn.lrz.de:/nfs/web_tum/www/n/di35non/webserver/htdocs
  

pages:
  image: alpine:3.18
  stage: deploy
  needs:
  - job: production
    artifacts: true
  script:
  - rm -rf public
  - mkdir public
  - mv gitlab_pages_redirect.html public/index.html
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker
