image: ruby:2.5

variables:
  JEKYLL_ENV: production

test:
  stage: test
  script:
  - bundle config set --local path 'vendor/bundle'
  - bundle install
  - bundle exec jekyll build -d website
  artifacts:
    paths:
    - website/

pages:
  stage: deploy
  script:
  - mv website public
  artifacts:
    paths:
    - public
  needs:
  - job: test
    artifacts: true
  only:
  - master
