# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BACI
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  BACI is an in-house research code to solve challenging computational multi-physics problems.
  It is jointly developed by several research groups across Germany.
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://baci.pages.gitlab.lrz.de" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
gitlab_username:  pages

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]
